auth:
  key: "XXXX-XXXX-XXXX-XXXX-XXXX"
  
server:
  port: 3000
  host: "localhost"
  session_secret: "your-session-secret"

database:
  mongodb_uri: "mongodb://localhost:27017/Hex-Share"

discord:
  bot_token: "Your Bot Token"
  client_id: "Your Client ID"
  client_secret: "Your Client Secret"
  callback_url: "http://localhost:3000/auth/discord/callback"
  guild_id: "Your Guild ID"
  logChannelId: "Your Log Channel ID"
  botIconUrl: "https://hexarion.net/Hex-L-T.png"
  embedColor: "#6366f1"

storage:
  upload_dir: "./uploads"
  max_file_size: 100000000 # 100MB
  allowed_types:
    - "image/*"
    - "application/pdf"
    - "application/zip"
    - "text/*"
tiers:
  premium:
    name: "Premium Elite"
    icon: "fa-crown"
    storage_limit: 10737418240 # 10GB
    badge_class: "premium-badge"
    users:
      - "Your Discord ID"
  
  standard:
    name: "Standard Plus"
    icon: "fa-star"
    storage_limit: 5368709120 # 5GB
    badge_class: "standard-badge"
    users:
      - "Your Discord ID"
  
  free:
    name: "Free User"
    icon: "fa-user"
    storage_limit: 1073741824 # 1GB
    badge_class: "free-badge"
    users: [] # Empty array means all other users default to free tier

analytics:
  google:
    enabled: true
    tracking_id: "G-XXXXXXXXXX"

footer:
  company_name: "Hex Share"
  tagline: "Your Next-Gen File Sharing Solution"
  social_links:
    github: "https://hexarion.net/github"
    discord: "https://hexarion.net/discord"
    YourTube: "https://hexarion.net/youtube"
  links:
    privacy: "https://hexarion.net/privacy-policy"
    terms: "https://hexarion.net/tos"
    contact: "https://hexarion.net/discord"
